import sys
import os
import sympy as sp
from taylor_expansion import compute_taylor_series

def generate_julia_initial_box(order=10):
    print(f"Generating Taylor series up to order {order}...")
    solutions, a_coeffs, b_coeffs, f_coeffs = compute_taylor_series(order=order)
    
    # We want to output a Julia function
    julia_code = [
        "# This file is AUTO-GENERATED by src/generate_julia_box.py",
        "# It contains the exact Taylor expansion polynomials.",
        "",
        "function compute_initial_box(a0, f2, eps)",
        "    # Taylor Coefficients"
    ]
    
    # Sort keys for consistent output
    a0_sym = sp.Symbol('a0')
    f2_sym = sp.Symbol('f2')
    
    for var, expr in solutions.items():
        # Convert sympy expression to string, then replace ** with ^ for Julia
        expr_str = str(expr).replace('**', '^')
        julia_code.append(f"    {var} = {expr_str}")
        
    julia_code.append("\n    # State at r = eps")
    
    # Create the series strings
    a_series = f"a0 + " + " + ".join([f"a{k} * eps^{k}" for k in a_coeffs if k > 0])
    a_prime_series = " + ".join([f"({k} * a{k}) * eps^{k-1}" for k in a_coeffs if k > 0])
    
    b_series = f"eps + " + " + ".join([f"b{k} * eps^{k}" for k in b_coeffs if k > 1])
    b_prime_series = "1 + " + " + ".join([f"({k} * b{k}) * eps^{k-1}" for k in b_coeffs if k > 1])
    
    f_series = " + ".join([f"f{k} * eps^{k}" for k in f_coeffs if k > 0])
    f_prime_series = " + ".join([f"({k} * f{k}) * eps^{k-1}" for k in f_coeffs if k > 0])
    
    julia_code.append(f"    a_eps = {a_series}")
    julia_code.append(f"    a_prime_eps = {a_prime_series}")
    julia_code.append(f"    b_eps = {b_series}")
    julia_code.append(f"    b_prime_eps = {b_prime_series}")
    julia_code.append(f"    f_eps = {f_series}")
    julia_code.append(f"    f_prime_eps = {f_prime_series}")
    
    julia_code.append("\n    # Step 4: Analytic majorant bounds (Geometric Tail)")
    julia_code.append("    # Note: K and C must be rigorously proven on paper.")
    julia_code.append("    # Current values are placeholders until the proof is complete.")
    julia_code.append("    K = 0.85   # Certified majorant multiplier")
    julia_code.append("    C = 0.6  # Certified geometric growth rate")
    julia_code.append("    ")
    julia_code.append("    remainder_bound = K * (C * eps)^11 / (1 - C * eps)")
    julia_code.append("    derivative_bound = 11 * K * C^11 * eps^10 / (1 - C * eps)")
    julia_code.append("    ")
    julia_code.append("    err_a = remainder_bound")
    julia_code.append("    err_a_prime = derivative_bound")
    julia_code.append("    err_b = remainder_bound")
    julia_code.append("    err_b_prime = derivative_bound")
    julia_code.append("    err_f = remainder_bound")
    julia_code.append("    err_f_prime = derivative_bound")
    
    julia_code.append("\n    # Return as intervals (Requires IntervalArithmetic.jl)")
    julia_code.append("    return [")
    julia_code.append("        interval(a_eps - err_a, a_eps + err_a),")
    julia_code.append("        interval(a_prime_eps - err_a_prime, a_prime_eps + err_a_prime),")
    julia_code.append("        interval(b_eps - err_b, b_eps + err_b),")
    julia_code.append("        interval(b_prime_eps - err_b_prime, b_prime_eps + err_b_prime),")
    julia_code.append("        interval(f_eps - err_f, f_eps + err_f),")
    julia_code.append("        interval(f_prime_eps - err_f_prime, f_prime_eps + err_f_prime)")
    julia_code.append("    ]")
    julia_code.append("end")
    
    # Write to file
    out_path = os.path.join(os.path.dirname(__file__), 'initial_box.jl')
    with open(out_path, 'w') as f:
        f.write("\n".join(julia_code))
    
    print(f"Successfully generated {out_path}!")

if __name__ == "__main__":
    generate_julia_initial_box(10)
