# This file is AUTO-GENERATED by src/generate_julia_box.py
# It contains the exact Taylor expansion polynomials.

function compute_initial_box(a0, f2, eps)
    # Taylor Coefficients
    a2 = a0/6
    b3 = (3*f2 + 1)/18
    a4 = a0*(24*f2 + 5)/1080
    f4 = 2*f2*(3*f2 + 1)/45
    b5 = (261*f2^2 + 66*f2 + 5)/5400
    a6 = a0*(3312*f2^2 + 1272*f2 + 35)/680400
    f6 = f2*(414*f2^2 + 114*f2 + 25)/14175
    b7 = (70281*f2^3 + 16173*f2^2 + 4167*f2 + 35)/4762800
    a8 = a0*(692928*f2^3 + 373248*f2^2 + 34800*f2 + 175)/571536000
    f8 = f2*(3609*f2^3 + 957*f2^2 + 463*f2 - 35)/496125
    b9 = (23584527*f2^4 + 5492124*f2^3 + 2491002*f2^2 - 44580*f2 + 175)/5143824000
    a10 = a0*(546331392*f2^4 + 365166144*f2^3 + 64183392*f2^2 + 2489520*f2 + 1925)/1697461920000
    f10 = f2*(4268214*f2^4 + 1170693*f2^3 + 825129*f2^2 - 87195*f2 + 21175)/2210236875
    b11 = (26889786351*f2^5 + 6611198049*f2^4 + 4156509870*f2^3 - 136575558*f2^2 + 59390595*f2 + 1925)/18672081120000

    # State at r = eps
    a_eps = a0 + a2 * eps^2 + a4 * eps^4 + a6 * eps^6 + a8 * eps^8 + a10 * eps^10
    a_prime_eps = (2 * a2) * eps^1 + (4 * a4) * eps^3 + (6 * a6) * eps^5 + (8 * a8) * eps^7 + (10 * a10) * eps^9
    b_eps = eps + b3 * eps^3 + b5 * eps^5 + b7 * eps^7 + b9 * eps^9 + b11 * eps^11
    b_prime_eps = 1 + (3 * b3) * eps^2 + (5 * b5) * eps^4 + (7 * b7) * eps^6 + (9 * b9) * eps^8 + (11 * b11) * eps^10
    f_eps = f2 * eps^2 + f4 * eps^4 + f6 * eps^6 + f8 * eps^8 + f10 * eps^10
    f_prime_eps = (2 * f2) * eps^1 + (4 * f4) * eps^3 + (6 * f6) * eps^5 + (8 * f8) * eps^7 + (10 * f10) * eps^9

    # Step 4: Analytic majorant bounds (Geometric Tail)
    # Note: K and C must be rigorously proven on paper.
    # Current values are placeholders until the proof is complete.
    K = 1.0   # Placeholder majorant multiplier
    C = 10.0  # Placeholder geometric growth rate
    
    remainder_bound = K * (C * eps)^11 / (1 - C * eps)
    derivative_bound = 11 * K * C^11 * eps^10 / (1 - C * eps)
    
    err_a = remainder_bound
    err_a_prime = derivative_bound
    err_b = remainder_bound
    err_b_prime = derivative_bound
    err_f = remainder_bound
    err_f_prime = derivative_bound

    # Return as intervals (Requires IntervalArithmetic.jl)
    return [
        interval(a_eps - err_a, a_eps + err_a),
        interval(a_prime_eps - err_a_prime, a_prime_eps + err_a_prime),
        interval(b_eps - err_b, b_eps + err_b),
        interval(b_prime_eps - err_b_prime, b_prime_eps + err_b_prime),
        interval(f_eps - err_f, f_eps + err_f),
        interval(f_prime_eps - err_f_prime, f_prime_eps + err_f_prime)
    ]
end